USE [master]
GO

/****** Object:  Database [ScandicFlags]    Script Date: 03/31/2017 00:06:55 ******/
CREATE DATABASE [ScandicFlags] ON  PRIMARY 
( NAME = N'ScandicFlags', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.JTTOCC\MSSQL\DATA\ScandicFlags.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ScandicFlags_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.JTTOCC\MSSQL\DATA\ScandicFlags_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ScandicFlags] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ScandicFlags].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ScandicFlags] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ScandicFlags] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ScandicFlags] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ScandicFlags] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ScandicFlags] SET ARITHABORT OFF 
GO

ALTER DATABASE [ScandicFlags] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ScandicFlags] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ScandicFlags] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ScandicFlags] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ScandicFlags] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ScandicFlags] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ScandicFlags] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ScandicFlags] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ScandicFlags] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ScandicFlags] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ScandicFlags] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ScandicFlags] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ScandicFlags] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ScandicFlags] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ScandicFlags] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ScandicFlags] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ScandicFlags] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ScandicFlags] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ScandicFlags] SET  READ_WRITE 
GO

ALTER DATABASE [ScandicFlags] SET RECOVERY FULL 
GO

ALTER DATABASE [ScandicFlags] SET  MULTI_USER 
GO

ALTER DATABASE [ScandicFlags] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ScandicFlags] SET DB_CHAINING OFF 
GO

